# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://2k22cse133_db_user:1LkxDgAMvVESZ9J7@quickbite.lj1bjbt.mongodb.net/quickbite?retryWrites=true&w=majority&appName=quickbite

# Server Port
server.port=8080

# JWT Config
jwt.secret=quickbite_secret_key_for_jwt_2026_hackathon_very_long
jwt.expiration=86400000

# CORS Configuration
spring.mvc.cors.allowed-origins=http://localhost:3000